executor: slurm
jobs: 100
cores: 960
latency-wait: 60

use-conda: true
conda-prefix: "/proj/sc_ml/shared/envs"

set-threads:
  run_sconce2: 32
  run_medicc2: 16

set-resources:
  run_sconce2:
    runtime: 720
    mem_mb: 96000
  run_medicc2:
    runtime: 400
    mem_mb: 40000

default-resources:
  mem_mb_per_cpu: 4000
  runtime: 30
  slurm_account: "naiss2026-3-168"
